version: "3.8"

services: 
  server:
    hostname: 'server'
    # image: 'nginx:stable-alpine'
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports: 
      - '8000:80'
    volumes: 
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: 
      - php
      - mysql
  php:
    hostname: 'php'
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes: 
      - ./src:/var/www/html:delegated 
    env_file:
      - docker/dev.env    
  mysql:
    hostname: 'mysql'
    image: mysql:8.0
    ports:
      - 3366:3306
    env_file: 
      - ./env/mysql.env
    volumes:
      - ./storage/mysql:/var/lib/mysql  
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes: 
      - ./src:/var/www/html
  # npm:
  #   image: node:14
  #   working_dir: /var/www/html
  #   entrypoint: ["npm"]
  #   volumes: 
  #     - ./src:/var/www/html
volumes:
    mysqldev1:
# networks:
#   dev1Network:
#     name: localDev1Network